[project]
name = "project10-course-work4-skypro"
version = "0.1.0"
description = ""
authors = [
    {name = "Margarita Bursheva",email = "mbursheva@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.5,<7.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "pillow (>=12.2.0,<13.0.0)",
    "ipython (>=9.13.0,<10.0.0)",
    "redis (>=7.4.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
exclude = 'venv'

[tool.black]
target-version = ['py313']
line-length = 119
exclude = '.git'

[tool.isort]
line_length = 119
[tool.poetry.group.dev.dependencies]
mypy = "^2.1.0"
black = "^26.5.0"
isort = "^8.0.1"
flake8 = "^7.3.0"

