# Generated by Django 6.0.5 on 2026-05-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Время начала")),
                ("end_time", models.DateTimeField(verbose_name="Время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(related_name="mailings", to="mailings.client", verbose_name="Получатели"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="mailings.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailings.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылок",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["-attempt_time"],
            },
        ),
    ]
