# Generated by Django 6.0.5 on 2026-05-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_mailing_options_client_owner_mailing_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_view_all_clients", "Может просматривать всех клиентов"),
                    ("can_view_users", "Может просматривать список пользователей"),
                    ("can_block_users", "Может блокировать пользователей"),
                    ("can_disable_mailings", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
